# This workflow will install Python dependencies, run tests present in the jupyter notebooks
# of the Python package, based on tutorials.

name: Python package notebooks

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python tests for notebooks
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install .
      - name: Run tests
        run: |
          # sudo apt-get update && sudo apt-get install -y texlive-latex-base texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra
          sudo apt-get update
          sudo apt-get install -y texlive-latex-base texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra cm-super dvipng texlive-latex-extra texlive-latex-recommended
          python -m pip install nbval
          pytest --nbval tutorials/GWs_sound-waves.ipynb